baseURL = 'https://maddybruster.com/'
languageCode = 'en-us'
title = 'Maddy Bruster'
buildFuture = true

[params]
  showDevSections = false

ignoreFiles = ['\.tmp\.\d+\.[0-9a-f]+$']

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false
  codeFences = true

[outputs]
  home = ["HTML"]

[permalinks]
  projects = "/:slug/"

